mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # url(r'^flowchart/', include('flowchart.urls')),
    url(r'^polls/', include('polls.urls')),
   
    url(r'^projectnote/', include('projectnote.urls')),
    url(r'^app001/', include('app001.urls')),
    #
    url(r'^admin/', admin.site.urls),
    url(r'', include('portal.urls')),

]

mysite/polls/urls.py
#polls/urls.py

from django.conf.urls import url

from . import views

app_name = 'polls'
# urlpatterns = [
#     # ex: /polls/
#     url(r'^$', views.index, name='index'),
#     # ex: /polls/5/
#     url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
#     # ex: /polls/5/results/
#     url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
#     # ex: /polls/5/vote/
#     url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

#     # url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
# ]
urlpatterns = [
    # url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^sop$', views.sop, name='sop'),
    url(r'^sop/(?P<sop_id>[0-9]+)/$', views.sop_detail, name='sop_detail'),



    url(r'^$', views.index, name='index'),

   # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),




    url(r'^feedback/$', views.feedback, name='feedback'),
#     # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
#

    # url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

mysite/polls/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone
import datetime

# 2017-02-17 SOP start
class Sop(models.Model):
    code = models.CharField('流程编号',max_length=16)
    ver = models.CharField('版本',max_length=8)
    ver_date = models.DateField('修订日期')
    title = models.CharField(max_length=200)
    dept = models.CharField('负责单位',max_length=16)
    editor = models.CharField('修改人员',max_length=16)
    page_num = models.CharField('页次',max_length=16)
    intro = models.CharField('流程定义',max_length=200)
    is_active=models.BooleanField("是否活躍", default=True )
    diagram = models.CharField('流程图',max_length=200,default="mark002.svg")

class Sopitem(models.Model):
    sop= models.ForeignKey(Sop, models.SET_NULL, null=True)
    item_seq = models.IntegerField(default=0)
    item_text = models.CharField(max_length=600)
# 2017-02-17 SOP end    


class Question(models.Model):
    ISACTIVE_CHOICES = (
       ('Y','Y'),
       ('N','N'),
    )
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    # is_active=models.CharField("是否活躍", default='Y',choices = ISACTIVE_CHOICES,max_length=1 )
    is_active=models.BooleanField("是否活躍", default=True )
    def __str__(self):
        return self.question_text

    # def was_published_recently(self):
    #     return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    # https://docs.djangoproject.com/en/1.10/intro/tutorial05/
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    def is_future_blog(self):
        now = timezone.now()
        return self.pub_date > now


    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = '最近(?天)發佈的?'

    is_future_blog.admin_order_field = 'pub_date'
    is_future_blog.boolean = True
    is_future_blog.short_description = '預約帖?'

    is_active.admin_order_field = 'is_active'
    is_future_blog.boolean = True
    is_future_blog.short_description = 'Is it active?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    remark = models.CharField("Remark",default="..",max_length=200)
    
    def __str__(self):
        return self.choice_text

# class Choice2(models.Model):
#     # question = models.ForeignKey(Question)
#     username = models.CharField(max_length=200)
#     choice_text = models.IntegerField(default=0)
#     debug = models.CharField("Remark",default="..",max_length=200)
    
#     def __str__(self):
#         return self.choice_text

class Feedback(models.Model):
    # FEEDBACK_CHOICES = (
    #    ('可以','可以'),
    #    ('不行','不行'),
    #    ('不知道','不知道'),

    # )
    question = models.CharField("Question",default=".", max_length=200)
    feedback = models.CharField("回覆",default=".", max_length=200)
    username = models.CharField("用戶名",default=".",max_length=200)
    created = models.DateTimeField( auto_now=True)
    # votes = models.IntegerField(default=0)
    def __str__(self):
        return self.username

mysite/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import Choice, Question,Feedback,Sop
from django.views import generic
from django.utils import timezone

import time

# def index(request):
#     return HttpResponse("Hello, world. You're at the polls index.")

def index(request):
    latest_question_list = Question.objects.filter(is_active = True).order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)


def sop(request):
    item_list = Sop.objects.filter(is_active = True).order_by('code')[:500]
    context = {'item_list': item_list}
    return render(request, 'polls/sop_list.html', context)

def sop_detail(request, sop_id):
    sop = get_object_or_404(Sop, pk=sop_id)
    return render(request, 'polls/sop_detail.html', {'sop': sop})


def feedback(request):
    item_list = Feedback.objects.order_by('question','username',)[:500]
    context = {'item_list': item_list}
    return render(request, 'polls/feedback.html', context)



# def detail(request, question_id):
#     return HttpResponse("You're looking at question %s." % question_id)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


# def results(request, question_id):
#     response = "You're looking at the results of question %s."
#     return HttpResponse(response % question_id)
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

# def vote(request, question_id):
#     return HttpResponse("You're voting on question %s." % question_id)

# ...
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])

    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        user_info="【未登入】"
        if not request.user.is_authenticated:
            selected_choice.remark +="【未登入】"+" "+time.strftime("%Y-%m-%d %H:%M:%S")+" | "
            selected_choice.votes += 1


        else:
            user_info=request.user.last_name
            selected_choice.remark +=request.user.last_name+" "+time.strftime("%Y-%m-%d %H:%M:%S")+" | "
            selected_choice.votes += 1
    #     question = models.ForeignKey(Question, on_delete=models.CASCADE)
    # username = models.CharField(max_length=200)
    # choice_text = models.IntegerField(default=0)
    # debug
                                  # feeback_textfeeback_text
        # f=Feedback(question="XXX",feedback="YYY",username="ZZZ")
        f=Feedback(question=question,feedback=selected_choice,username=user_info)

        f.save()
        # choice2.save()
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


# class IndexView(generic.ListView):
#     template_name = 'polls/index.html'
#     context_object_name = 'latest_question_list'

# #     def get_queryset(self):
# #         """Return the last five published questions."""
# #         return Question.objects.order_by('-pub_date')[:5]

#     def get_queryset(self):
#         """
#         Return the last five published questions (not including those set to be
#         published in the future).
#         """
#         return Question.objects.filter(
#             pub_date__lte=timezone.now()
#         ).order_by('-pub_date')[:5]


# class DetailView(generic.DetailView):
#     model = Question

    # template_name = 'polls/detail.html'
	# https://docs.djangoproject.com/en/1.10/intro/tutorial04/
	# default one is no need to state, it's working!
    # template_name = 'polls/question_detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

mysite/polls/templates/polls/detail.html
<h1>xxx{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.votes }}票 :&nbsp;  {{ choice.choice_text }} &nbsp;  {{ choice.remark }}</li>
{% endfor %}


</ul>

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}


{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

mysite/polls/templates/polls/feedback.html
{% if item_list %}
    


    
    	<table bolder=1>
    {% for item in item_list %}
       <tr><td> {{ item.question }}</td><td>{{ item.username }}</td><td>{{ item.feedback }}</td><td>{{ item.create | date:"[Y-m-d h:i] " }}</td></tr>
    {% endfor %}
    </table>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/index.html
{% if latest_question_list %}
    


    <ul>
    {% for question in latest_question_list %}
       <li>{{ question.is_active }} {{ question.pub_date | date:"[Y-m-d h:i] " }}<a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/question_detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.votes }}票 :&nbsp;  {{ choice.choice_text }} </li>
{% endfor %}
</ul>

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
{{question}}
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>

        <li>{{ choice.votes }}票 :&nbsp;  {{ choice.choice_text }} &nbsp;  {{ choice.remark }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

mysite/polls/templates/polls/sop_detail.html
<table>
    
    <tr>
      <td> 流程编号 </td> 
      <td>{{ sop.code }} </td> 
      <td rowspan="3"><h3>{{ sop.title }} <h3></td>  
      <td>负责单位</td>
      <td>{{ sop.dept }} </td>      
    </tr>

    <tr>
       <!-- <td> <a href='sop/{{ sop.id }}' > {{ sop.title }}<a> </td> -->
      <td>版本</td>
       <td>ver {{ sop.ver}} </td>
        <td>修改人员</td>
     <td>{{ sop.editor }} </td>
      </tr>
    
    <tr> 
         <td>修订日期</td>
         <td>{{ sop.ver_date | date:"Y-m-d" }} </td>
       
       <td>页次</td>
       <td>{{ sop.page_num}} </td>
    </tr>
      <tr> 
      	<td>流程定义</td>
     
       <td colspan='4'>{{ sop.intro }} </td>
    </tr>
   
    </table>
<img src="/static/polls/{{ sop.diagram }}"  alt="Testing svg" />
<table>
{% for item in sop.sopitem_set.all %}
    <tr>
    	<td>    	{{ item.item_seq }}       </td>
    	<td>    	{{ item.item_text }}        </td>
    </tr>
{% endfor %}


</table>

mysite/polls/templates/polls/sop_list.html
{% if item_list %}
   

    <table>
    {% for item in item_list %}
    <tr>
       <td>{{ item.code }} </td>         
    
       <td> <a href='sop/{{ item.id }}' > {{ item.title }}<a> </td>
       <!-- <td>{{ item.title }} </td> -->
       <td>ver {{ item.ver}} </td>
       <td>{{ item.ver_date | date:"Y-m-d" }} </td>
       <td>{{ item.dept }} </td>
       <td>{{ item.editor }} </td>
       <td>{{ item.intro }} </td>
    </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No SOP are available.</p>
{% endif %}

<!--  code = models.CharField('流程编号',max_length=16)
    ver = models.CharField('版本',max_length=8)
    ver_date = models.DateField('修订日期')
    title = models.CharField(max_length=200)
    dept = models.CharField('负责单位',max_length=16)
    editor = models.CharField('修改人员',max_length=16)
    page_num = models.CharField('页次',max_length=16)
    intro = models.CharField('流程定义',max_length=200)
    diagram = models.ImageField('流程图',null=True)
    is_active=models.BooleanField("是否活躍", default=True ) -->